// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YmmoApi.Data;

#nullable disable

namespace YmmoApi.Migrations
{
    [DbContext(typeof(YmmoDbContext))]
    [Migration("20260613225034_AddFavorites")]
    partial class AddFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YmmoApi.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Rue de la République",
                            City = "Aix-en-Provence",
                            Email = "aix@ymmo.fr",
                            Name = "Ymmo Aix-en-Provence",
                            Phone = "+33 4 42 00 00 01"
                        },
                        new
                        {
                            Id = 2,
                            Address = "3 Avenue des Champs-Élysées",
                            City = "Paris",
                            Email = "paris@ymmo.fr",
                            Name = "Ymmo Paris",
                            Phone = "+33 1 42 00 00 02"
                        },
                        new
                        {
                            Id = 3,
                            Address = "15 Rue de la République",
                            City = "Lyon",
                            Email = "lyon@ymmo.fr",
                            Name = "Ymmo Lyon",
                            Phone = "+33 4 72 00 00 03"
                        },
                        new
                        {
                            Id = 4,
                            Address = "8 La Canebière",
                            City = "Marseille",
                            Email = "marseille@ymmo.fr",
                            Name = "Ymmo Marseille",
                            Phone = "+33 4 91 00 00 04"
                        },
                        new
                        {
                            Id = 5,
                            Address = "22 Cours de l'Intendance",
                            City = "Bordeaux",
                            Email = "bordeaux@ymmo.fr",
                            Name = "Ymmo Bordeaux",
                            Phone = "+33 5 56 00 00 05"
                        });
                });

            modelBuilder.Entity("YmmoApi.Models.AgencyMonthlyRevenue", b =>
                {
                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<long>("RankInAgency")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("YmmoApi.Models.AvailablePropertyListing", b =>
                {
                    b.Property<string>("AgencyCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DpeRating")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ListedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_biens_disponibles", (string)null);
                });

            modelBuilder.Entity("YmmoApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("YmmoApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("YmmoApi.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("YmmoApi.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("YmmoApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DpeRating")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ListedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("AgentId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            Area = 73.5,
                            Bedrooms = 2,
                            City = "Aix-en-Provence",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 321, DateTimeKind.Utc).AddTicks(8096),
                            Description = "Superbe appartement de 73m² en plein cœur d'Aix, lumineux, double exposition. Cuisine équipée, parquet, cave. Idéal investisseur ou première acquisition.",
                            ListedDate = new DateOnly(2026, 5, 10),
                            Price = 320000m,
                            Status = "Available",
                            Title = "Appartement T3 Centre Historique",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 2,
                            Area = 120.0,
                            Bedrooms = 0,
                            City = "Paris",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2592),
                            Description = "Espace de bureaux modulable en zone commerciale premium. Accès PMR, parking, fibre. Idéal pour startup ou PME.",
                            ListedDate = new DateOnly(2026, 4, 25),
                            Price = 420000m,
                            Status = "Available",
                            Title = "Bureau Open-Space 120m²",
                            Type = "Commercial"
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 3,
                            Area = 142.19999999999999,
                            Bedrooms = 4,
                            City = "Lyon",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2598),
                            Description = "Belle maison de 4 chambres avec jardin de 300m², garage double, piscine. Quartier calme proche écoles et commerces.",
                            ListedDate = new DateOnly(2026, 4, 15),
                            Price = 580000m,
                            Status = "UnderOffer",
                            Title = "Maison Familiale avec Jardin",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 4,
                            AgencyId = 4,
                            Area = 95.0,
                            Bedrooms = 2,
                            City = "Marseille",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2601),
                            Description = "Loft de caractère 95m² en plein Vieux-Port. Hauteur sous plafond 4m, briques apparentes, cuisine ouverte. Coup de cœur garanti.",
                            ListedDate = new DateOnly(2026, 5, 20),
                            Price = 485000m,
                            Status = "Available",
                            Title = "Loft Industriel Rénové",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 5,
                            AgencyId = 5,
                            Area = 280.0,
                            Bedrooms = 5,
                            City = "Bordeaux",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2604),
                            Description = "Villa contemporaine 5 chambres, piscine à débordement, vue imprenable sur la Garonne. Prestations haut de gamme.",
                            ListedDate = new DateOnly(2026, 3, 1),
                            Price = 1250000m,
                            Status = "Available",
                            Title = "Villa Prestige Vue Garonne",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 6,
                            AgencyId = 1,
                            Area = 28.0,
                            Bedrooms = 1,
                            City = "Aix-en-Provence",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2606),
                            Description = "Studio meublé 28m², idéalement placé à 200m de l'université. Charges incluses, bail étudiant ou classique.",
                            ListedDate = new DateOnly(2026, 5, 28),
                            Price = 125000m,
                            Status = "Available",
                            Title = "Studio Étudiant Centre-Ville",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 7,
                            AgencyId = 2,
                            Area = 800.0,
                            Bedrooms = 0,
                            City = "Paris",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2609),
                            Description = "Entrepôt neuf en ZAC, hauteur 8m, 4 quais de chargement, bureau intégré 50m². Bail 3/6/9 ans.",
                            ListedDate = new DateOnly(2026, 2, 14),
                            Price = 890000m,
                            Status = "Available",
                            Title = "Entrepôt Logistique 800m²",
                            Type = "Commercial"
                        },
                        new
                        {
                            Id = 8,
                            AgencyId = 3,
                            Area = 118.0,
                            Bedrooms = 3,
                            City = "Lyon",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2615),
                            Description = "T4 de standing 118m² au 6ème étage avec terrasse 30m². Vue panoramique, gardien, cave, 2 parkings.",
                            ListedDate = new DateOnly(2026, 1, 10),
                            Price = 695000m,
                            Status = "Sold",
                            Title = "Appartement T4 Prestige",
                            Type = "Residential"
                        },
                        new
                        {
                            Id = 9,
                            AgencyId = 4,
                            Area = 650.0,
                            Bedrooms = 0,
                            City = "Marseille",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2617),
                            Description = "Terrain plat viabilisé dans lotissement sécurisé. Permis de construire accordé pour villa R+1. Environnement verdoyant.",
                            ListedDate = new DateOnly(2026, 5, 5),
                            Price = 198000m,
                            Status = "Available",
                            Title = "Terrain Constructible 650m²",
                            Type = "Land"
                        },
                        new
                        {
                            Id = 10,
                            AgencyId = 5,
                            Area = 160.0,
                            Bedrooms = 3,
                            City = "Bordeaux",
                            CreatedAt = new DateTime(2026, 6, 13, 22, 50, 33, 322, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Duplex 160m² avec rooftop privatif 80m² face au Cours du Chapeau Rouge. Architecture contemporaine, matériaux nobles.",
                            ListedDate = new DateOnly(2026, 4, 8),
                            Price = 875000m,
                            Status = "Available",
                            Title = "Duplex Rooftop Exceptceptionnel",
                            Type = "Residential"
                        });
                });

            modelBuilder.Entity("YmmoApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("YmmoApi.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("YmmoApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("YmmoApi.Models.TransactionDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDocuments");
                });

            modelBuilder.Entity("YmmoApi.Models.TransactionStageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionStageHistories");
                });

            modelBuilder.Entity("YmmoApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YmmoApi.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("YmmoApi.Models.Favorite", b =>
                {
                    b.HasOne("YmmoApi.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YmmoApi.Models.Message", b =>
                {
                    b.HasOne("YmmoApi.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("YmmoApi.Models.Photo", b =>
                {
                    b.HasOne("YmmoApi.Models.Property", "Property")
                        .WithMany("Photos")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YmmoApi.Models.Property", b =>
                {
                    b.HasOne("YmmoApi.Models.Agency", "Agency")
                        .WithMany("Properties")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("YmmoApi.Models.RefreshToken", b =>
                {
                    b.HasOne("YmmoApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YmmoApi.Models.Sale", b =>
                {
                    b.HasOne("YmmoApi.Models.Client", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.Client", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Property");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("YmmoApi.Models.Transaction", b =>
                {
                    b.HasOne("YmmoApi.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YmmoApi.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YmmoApi.Models.TransactionDocument", b =>
                {
                    b.HasOne("YmmoApi.Models.Transaction", "Transaction")
                        .WithMany("Documents")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("YmmoApi.Models.TransactionStageHistory", b =>
                {
                    b.HasOne("YmmoApi.Models.Transaction", "Transaction")
                        .WithMany("StageHistory")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("YmmoApi.Models.User", b =>
                {
                    b.HasOne("YmmoApi.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("YmmoApi.Models.Visit", b =>
                {
                    b.HasOne("YmmoApi.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YmmoApi.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoApi.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YmmoApi.Models.Agency", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YmmoApi.Models.Property", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("YmmoApi.Models.Transaction", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("StageHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
